export const GET_USERS_INITIATED = "GET_USERS_INITIATED"
export const GET_USERS_COMPLETED = "GET_USERS_COMPLETED"
export const GET_POSTS_INITIATED = "GET_POSTS_INITIATED"
export const GET_POSTS_COMPLETED = "GET_POSTS_COMPLETED"